### ISSUE TITLE
Ensure support for simphony-common 0.3.0

### ISSUE THREAD

**Issue by kitchoi** [simphony/simphony-paraview#33]

**Comment by stefanoborini** [comment]
From what I understand, 0.3.0 added materials. Do we need to support them, and if yes, how are they supposed to be represented?

In any case, any change on this regard need to be integrated in cuds2vtk and subfunctions.

**Comment by kitchoi** [comment]
There is no proposal, as far as I know, for adding exclusive support for visualising `Material` class.   Side note: `Material` will be one of the generated meta classes in 0.4.0

**Comment by stefanoborini** [comment]
So there's nothing to be done on this topic?

**Comment by kitchoi** [comment]
Yes, we need to have the repo tested against simphony-common 0.3.0 on travis, see #36

**Comment by kitchoi** [comment]
ahaha by 'yes' I mean there is something to be done 🙈

**Comment by stefanoborini** [comment]
@kitchoi ok but this means that the PR is already there. It's only not green because of the known problem with paraview, but if I get it to green and there are no other problems I can merge it and close this one.

**Comment by stefanoborini** [comment]
PR #36 is green. Closing
