### ISSUE TITLE
Simphony-paraview does not install itself appropriately as simphony plugin

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-paraview#38]
I currently installed both simphony-mayavi and simphony-paraview. The plugin system supported by stevedore should make them available under simphony.visualisation. The entry points are correctly configured for both, however...

This is a list of the pip installed packages (removed all the unnecessary ones)

```
mayavi (4.5.0.dev0, /Users/sborini/Work/github/enthought/mayavi)
simphony (0.3.1.dev0, /Users/sborini/Work/github/simphony/simphony-common)
simphony-mayavi (0.4.2.dev17, /Users/sborini/Work/github/simphony/simphony-mayavi)
simphony-paraview (0.2.1.dev8, /Users/sborini/.edm/envs/simphony/lib/python2.7/site-packages/simphony_paraview-0.2.1.dev8-py2.7.egg)
stevedore (1.17.0)
```

I installed simphony-mayavi as develop and simphony-paraview as non-develop, but I also tried both as develop and didn't solve.

If I import `simphony_paraview` from the python prompt it correctly imports the package. 
If I import `simphony.visualisation`, the `load_visualisation_extensions()` function correctly sees `mayavi_tools` in the extensions, but not `paraview_tools`.

**Comment by stefanoborini** [comment]
Note that I have this behavior only on my mac. On travis seems to work, so I suspect some incorrect path somewhere. I am using edm, so that could also be a reason.

**Comment by stefanoborini** [comment]
confirmed also on linux. Investigating.

**Comment by stefanoborini** [comment]
Closing, but leaving an indication for future reference.

When this happens, it's generally because the import of paraview failed. Stevedore is not very helpful when it comes to tracking down why a given plugin didn't show up. The quick and dirty way of getting to the problem is to print what happens in stevedore.extension.ExtensionManager() and move on from there.

**Comment by itziakos** [comment]
As fas as I know it is a know problem that you cannot have simphony-paraview and simphony-mayavi at the same time. https://github.com/simphony/simphony-mayavi#known-issues. A similar comment in the simphony-paraview readme should be fine
