### ISSUE TITLE
Presence of vtk5.8 interferes with paraview4 vtk (6.0)

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-paraview#42]
If vtk5.8 (with python module) is present and paraview4 is used, the resulting combination breaks the plugin. This is masked by stevedore and can result in #38 (although many possibilities can produce that result).

The problem is the following. In compatibility.py vtk objects are imported when paraview is version 4. Unfortunately if the imported vtk module is 5.8 this will create a strange situation where (see set_input) the paraview version returns 6.0, but the objects are from 5.8.

I tried to fix this by simply changing the import, but it resulted in incorrect import of the objects.

I am opening a PR attempting to solve this issue, but I am unsure if it breaks other combinations, and I am unsure what the intention and assumptions made when that part was written.

@itziakos ?

**Comment by itziakos** [comment]
Paraview does not use the system vtk, this is a problem of the paraview package in ubuntu (if not with paraview build and packaging itself). This is issue is not a bug of simphony-paraview or simphony-mayavi  since we have a limited space to workaround such issues.

**Comment by itziakos** [comment]
> This is masked by stevedore

For debugging such problems one can replicate the issue by attempting to load the related modules in an ipython prompt.
